name: setNamePlugin
main: nameSet\nameSet
version: 0.1
api:
    - 1.13.1
    - 2.0.0
author: Redstonealmeida

commands:
    setplayernick:
        description: setplayernick
        use: "/setplayernick"
        permission: setplayernick.command

permission:
    setplayernick.command:
    description: "setplayernick"
    default: op
